edit README.md
pieces-app/plugin_sublime pull request #100
Opened 2024-06-24 10:38 UTC by Bishoy-at-pieces

2024-06-24 17:23 UTC, caleb-at-pieces approved these changes

2024-06-24 19:58 UTC, shivay-at-pieces requested changes
The starting

2024-06-24 19:58 UTC, shivay-at-pieces commented on README.md
> -## Getting Started
The Pieces Sublime Plugin logo should have the image similar to other plugins: https://github.com/pieces-app/obsidian-pieces/raw/main/assets/readme/pfd-obisidan-plugin-hero.png

2024-06-24 19:59 UTC, shivay-at-pieces commented on README.md
> -## Getting Started
@laurin-at-pieces can provide the image for Sublime plugin

2024-06-24 20:07 UTC, mack-at-pieces requested changes

2024-06-24 20:07 UTC, mack-at-pieces commented on README.md
> +### Right Click to Add an Asset
"Right Click to Save to Pieces"

2024-06-24 20:07 UTC, mack-at-pieces commented on README.md
> +### Right Click to Add an Asset
Can we make this one first in the order AFTER "Configuration"

2024-06-24 20:07 UTC, mack-at-pieces commented on README.md
>  ### Copilot Ask
Can we make this one second in the order after "Save to Pieces"

2024-06-24 20:07 UTC, mack-at-pieces commented on README.md
> +### Open a Copilot Conversation
This one can be third

2024-06-24 20:07 UTC, mack-at-pieces commented on README.md
> +Ever wished for a personal coding assistant? Look no further! With Pieces Copilot, you can have an AI-powered assistant right at your fingertips. Simply open the command palette and select `Pieces: C
I think we should move this copy, "Ever wished for a personal coding assistant? Look no further! With Pieces Copilot, you can have an AI-powered assistant right at your fingertips." into the "Copilot Ask" section.

"Ever wished for a personal coding assistant? Look no further! With Pieces Copilot, you can have an AI-powered assistant right at your fingertips. Whether it's commenting, fixing a bug, or adding a docstring, just select the code, right-click to open the context menu, and choose `Pieces > Ask Copilot`. Let Copilot do the heavy lifting for you!"

2024-06-24 20:07 UTC, mack-at-pieces commented on README.md
> +Ever wished for a personal coding assistant? Look no further! With Pieces Copilot, you can have an AI-powered assistant right at your fingertips. Simply open the command palette and select `Pieces: C
Then this one can be more oriented around viewing their existing conversations.. 

"Need to open an existing Copilot Chat, or start a new one? Simply open the command palette and select `Pieces: Copilot`. ..."

2024-06-24 20:07 UTC, mack-at-pieces commented on README.md
>  ### Copilot Ask
"Engage with the Pieces Copilot"

2024-06-25 08:21 UTC, Bishoy-at-pieces commented
@mack-at-pieces seems I did not explain well the difference between the "Ask" and the "Copilot Ask" 
the ask from the context menu I think I need better description for the "Copilot Ask"
![image](https://github.com/pieces-app/plugin_sublime/assets/167128903/0cd07e60-7c06-4074-9875-e6c093facd68)

and can you suggest me better name?

2024-06-27 21:07 UTC, mack-at-pieces commented on README.md
> +## Getting Started with Pieces Sublime Plugin
"Getting Started with the Pieces Sublime Plugin"

2024-06-27 21:07 UTC, mack-at-pieces commented on README.md
> +### Open Saved Material
"Open Saved Materials"

2024-06-27 21:07 UTC, mack-at-pieces commented on README.md
> +Need some help from Copilot? Whether it's commenting, fixing a bug, or adding a docstring, just select the code, right-click to open the context menu, and choose `Pieces > Ask Copilot`. Let Copilot d
"Need some help from the Pieces Copilot? ..."

2024-06-27 21:07 UTC, mack-at-pieces commented on README.md
>  ### Copilot Ask
"Use the Pieces Copilot to Modify Code or Solve Problems"

2024-07-08 05:19 UTC, shivay-at-pieces requested changes

2024-07-08 05:19 UTC, shivay-at-pieces commented on README.md
> +## Getting Started with the Pieces Sublime Plugin
Hey @Bishoy-at-pieces so keeping the readme streamlined like the other readmes for our plugins, 

You can start the readme this way: 
```
# [Pieces for Developers](https://pieces.app) | Sublime Plugin

Then the hero image 

## Overview 
What is the Sublime plugin

## Features

<!--   Add all of the features here --> 
```

2024-07-08 17:54 UTC, shivay-at-pieces approved these changes

2024-07-09 14:05 UTC, mack-at-pieces approved these changes

2024-07-09 15:50 UTC, merged