Add asset search
pieces-app/plugin_sublime pull request #45
Opened 2024-05-21 09:13 UTC by Bishoy-at-pieces

https://drive.google.com/file/d/1zFKEUIq-Q3qhVFAWJA9uviUrK9hLH7ct/view?usp=sharing

2024-05-21 18:58 UTC, caleb-at-pieces requested changes
it looks like we have an extra placeholder method in one of the classes also we should probably break these classes into their own files

2024-05-21 18:58 UTC, caleb-at-pieces commented on search/search_command.py
> +		return "Enter a quick description of the bug itself or useful error message"
what is this placeholder for?

2024-05-21 18:58 UTC, caleb-at-pieces commented on search/search_command.py
> +			if isinstance(iterable_list, list) and all(hasattr(asset, 'exact') and hasattr(asset, 'identifier') for asset in iterable_list):
good job with null safety!

2024-05-21 18:59 UTC, Bishoy-at-pieces commented on search/search_command.py
> +		return "Enter a quick description of the bug itself or useful error message"
Yupp mb needs to be changed

2024-05-22 15:24 UTC, caleb-at-pieces approved these changes

2024-05-22 15:39 UTC, mark-at-pieces commented on search/search_command.py
> +			results = api_instance.neural_code_search(query=query)
might need to specify transferables on this as well but cant remember 100%

2024-05-22 15:40 UTC, mark-at-pieces approved these changes

2024-05-22 16:01 UTC, merged